### ISSUE TITLE
Google Speech API v2 access control

### ISSUE THREAD

**Issue by legend0011** [gillesdemey/google-speech-v2#11]
I would like to use Google Speech API v2 to generate asr(auto speech recognition) result for .wav files for experiment use.

I make some changes to a project on GitHub: https://github.com/Uberi/speech_recognition , And I apply for my own API key, and I can only access the API for about 500 times a day.

Do you know how to make 5000 or more request(access to the API)? Or how google block us??

Thanks very much !!!

**Comment by gillesdemey** [comment]
There are currently a few restrictions to the API, please take a look at the caveats section:
https://github.com/gillesdemey/google-speech-v2#caveats

There's currently no way to increase the number of requests you can make, they use your API key to determine how many API calls you have left. You can also check this in your Google dashboard.
