### ISSUE TITLE
 Getting always “1” in confidence result since last Wednesday

### ISSUE THREAD

**Issue by Danievon** [gillesdemey/google-speech-v2#13]
Hello everyone, I´m using google speech API v2, and it is very important for me to know the confidence but since last Wednesday it is always 1.  I wanna know if you have the same response.
Thanks 
Best regards

**Comment by davidfer1991** [comment]
Hello,

That's the same problem that I'm having since this week!

Anybody with a solution for this issue?

Thanks in advance

BR.
