### ISSUE TITLE
can not open the api link

### ISSUE THREAD

**Issue by csrgxtu** [gillesdemey/google-speech-v2#18]

**Comment by gillesdemey** [comment]
Can you be more descriptive? What particular link does not work for you?

**Comment by jhoelzl** [comment]
Link in README.md is getting an 404 error: https://www.google.com/speech-api/v2/recognize

**Comment by gillesdemey** [comment]
That's a 400 error, you're lacking some parameters and there's no visual aspect to the speech API.
